### PR TITLE
Mmaelicke-remove-rest

### PR DESCRIPTION
**Pull request by mmaelicke**
This PR removes the very incomplete rest endpoint. We will add that back somewhere in the future, but maybe without the `Flask` dependency.

### CODE REVIEW

**Comment by mmaelicke** [comment]
Hmm, we had this error before, that the CLI does not return anything, right @AlexDo1 ?

Question is, was that related to the removal of `rest` submodule? I can't see a connection...

**Comment by AlexDo1** [comment]
Yes, we had that Error before, but I can't exactly recall how we fixed it.  
Here I made some changes in the branch `fix-cli`: https://github.com/VForWaTer/metacatalog/commit/e85070f219496a5e63ad0338fbac0a9d6199baa7

And here is a mentioning of REST in [command_line.py](https://github.com/VForWaTer/metacatalog/blob/main/metacatalog/command_line.py):
https://github.com/VForWaTer/metacatalog/blob/4d839049e57dbec40de94e0d8c8f47bd0f30e46d/metacatalog/command_line.py#L102-L107
But I have no idea if this could be a problem.

**Comment by mmaelicke** [comment]
@AlexDo1, now I found all references. The CLI is working fine locally and the tests also run. I guess you can review and then I can merge

**Review by AlexDo1 — APPROVED** [review]
Nice, looks good!

**Pull request merged**
