### PR TITLE
Added the EntryGroup "Split Dataset"

### PR DESCRIPTION
**Pull request by AlexDo1**

### CODE REVIEW

**Review by mmaelicke — CHANGES_REQUESTED** [review]
Looks good!
The only thing missing is the database revision. @AlexDo1 do you feel like you can do that yourself, or shall I do it quickly.
This revision might not be super-straightforward, as its not changing the structure, but the data in the database.

**Comment by AlexDo1** [comment]
I would like to try this, but I am not sure what to do.

I need to create a new file "rev4" and write some code for `UPGRADE_SQL` and `DONWGRADE_SQL`, right?
Which table would I have to change in metacatalog for the new EntryGroup?

The table entrygroup_types already looks (?):
image

**Comment by mmaelicke** [comment]
> I would like to try this, but I am not sure what to do.
> 
> I need to create a new file "rev4" and write some code for `UPGRADE_SQL` and `DONWGRADE_SQL`, right?

Yeah. But you also need to import and add the new file in the `/db/revisions/__init__.py` file. It's easier to use the metacatalog CLI for this:

```bash
python -m metacatalog migrate revision
```
That will include and add all needed files and you just need to update the file. 

> Which table would I have to change in metacatalog for the new EntryGroup?

For this revision, you don't change any Table. You need to add a new entry. Have a look at `rev3.py`, where `Person.uuid` is updated. This is how you can add a new entry. Alternatively, you can write the plain SQL and execute it. The SQL for adding is similar to:
```sql
INSERT into entrygroup_types (name, description) values ('Split dataset', 'Lorem Ipsum ..')
```
The downgrade command should remove this entry again:
```sql
DELETE FROM entrygroup_types where name='Split dataset';
```

Best,

**Comment by mmaelicke** [comment]
Perfect! I just merged this

**Comment by mmaelicke** [comment]
BTW.: It's really important to implement the SQL like you did it and not to rely on `id` fields. They are usually autofilled, and differ on the different systems. You can run the `python -m metacatalog migrate downgrade` and then the `python -m metacatalog migrate upgrade` command. After that, the new entry has another id...
Just to give you some background.

**Pull request merged**
