### PR TITLE
Add all Person Roles to Entry.to_dict

### LINKED ISSUE #215: Entry.to_dict() include Person roles
At the moment, Person roles are not included in `Entry.to_dict()`.  
E.g. for ISO export, having the roles of associated persons would be very helpful.  
The dictionary could be expanded by roles as keys with the Persons as values.
```python
{
   'authors': Person1,
   'coauthors': [Person2, Person3, Person4],
   'owner': Person5,
   ...
}
```

### PR DESCRIPTION
**Pull request by mmaelicke**
Closes #215

- [x] add to the `Entry.to_dict`method
- [x] change the `Entry.from_dict]` method
- [x] add a test for this behavior explicitly
- [x] check the `api.find_person` method for implementation
- ~check the `api.find_entry` method for implementation~

### CODE REVIEW

**Comment by AlexDo1** [comment]
I just found out that, `Entry.contributors` stills returns `PersonAssociations` instead of `Person` objects:
Bildschirmfoto vom 2023-01-31 14-16-16

**Comment by AlexDo1** [comment]
I added the tests, both fail.

1. Entry with 2 persons with role `pointOfContact`: `Entry.to_dict()['pointOfContact']` only returns 1 Person.
2. `Entry.from_dict(session, entry.to_dict())` should currently raise a `NotImplementedError`, as 'id' is in data, but instead, a SQLAlchemy error is raised (`sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.str' is not mapped`)
https://github.com/VForWaTer/metacatalog/blob/4db141b634ab6976f50ad6addb0d35007971aa36/metacatalog/models/entry.py#L292-L293

**Comment by mmaelicke** [comment]
@AlexDo1  Tests work now.

The second test failed because the signature of the function was actually:
 ```python
def from_dict(self, data:dict, session Session) -> 'Entry':
```

Thus, by using positional arguments, the test passed in the dict as session and the session as dict. I changed the test to use keyword argument explicitly, **but also changed the order of arguments!!*. Now, the session **is** the first argument, just like everywhere in the API.

**Comment by AlexDo1** [comment]
> Closes #215
> 
> * [x]  add to the `Entry.to_dict`method
> * [x]  change the `Entry.from_dict]` method
> * [x]  add a test for this behavior explicitly
> * [x]  check the `api.find_person` method for implementation
> * [ ]  check the `api.find_entry` method for implementation

Looks good, did you also check the last checkpoint of the list?

**Comment by mmaelicke** [comment]
> > Closes #215
> > 
> > * [x]   add to the `Entry.to_dict`method
> > * [x]   change the `Entry.from_dict]` method
> > * [x]   add a test for this behavior explicitly
> > * [x]   check the `api.find_person` method for implementation
> > * [ ]   check the `api.find_entry` method for implementation
> 
> Looks good, did you also check the last checkpoint of the list?

I am on it right now...
The `contributor=None` filter is actually doing the right thing, but filters for `author` and `coAuthor`only. I suggest to deprecate this argument and inform users to use the newly created `authors=None` filter. Then, with 0.8.0 or 0.9.0, the contributors will run the same code without the filter for authors only.
We should move this comment into a new issue.

**Comment by mmaelicke** [comment]
This one is ready for review now

**Review by AlexDo1 — APPROVED** [review]
This also looks good, nice that you started with the type hints!

**Pull request merged**
