### PR TITLE
added tests to find a person

### PR DESCRIPTION
**Pull request by AlexDo1**
Added tests to find a person person by uuid (`check_get_by_uuid()`) and created a new test to test the `find_person()` function.

It took me a while to figure out that the `find_person()` function directly returns a Person object when searching for a uuid and a list of Person objects when searching for other attributes like first_name. This makes sense, of course, since searching for attributes like names can have multiple results.

### CODE REVIEW

**Review by mmaelicke — APPROVED** [review]
Nice work! 
You can go ahead and merge this.

**Comment by AlexDo1** [comment]
I would like to merge, but there is still a check in progress.
Do you know what happens there?

image

**Comment by mmaelicke** [comment]
Never mind. It's the migration test that is failing. We still don't have the database migrated. I will do that soon

**Comment by AlexDo1** [comment]
Okay, but I think that I still don´t have the authorization to merge this PR (which is okay with me).

**Comment by mmaelicke** [comment]
Now it should be possible. Can you try again?

**Pull request merged**
