### PR TITLE
Check extension for missing dependencies

### LINKED ISSUE #277: ext.activate_extension: check required packages
We  need a import flag that indicates if all requirements were met. The extension activation function should then check if everything is there.
The user has to take care of that.

_Originally posted by @mmaelicke in https://github.com/VForWaTer/metacatalog/issues/264#issuecomment-1429693166_

### PR DESCRIPTION
**Pull request by mmaelicke**
closes #277

### CODE REVIEW

**Comment by AlexDo1** [comment]
I just tried to install metacatalog (`pip install -e .`) into a new conda environment and into a new venv environment to test this branch.  
In both cases, dependencies are installed but then it does not go any further and hangs in `Running setup.py develop for metacatalog`. This does not only happen with this branch but also with the main branch.  
I will try again tomorrow with a restarted computer, maybe the problem fixes itself...

**Comment by AlexDo1** [comment]
Okay, the `pip install -e .` issue was a problem with my computer, the installation went smoothly today.

When trying to activate the `standards_export` extension with missing dependencies in the environment, a `ModuleNotFoundError` is produced:
```python 
ext.activate_extension('standards_export', 'metacatalog.ext.standards_export', 'StandardsExportExtension')
```
image

Running `ext.__load_extensions()` also produces the expected `UserWarning`:
image

**Comment by AlexDo1** [comment]
@mmaelicke I will approve when you had a look at my previous comment and also confirm that everything works as expected.

**Comment by mmaelicke** [comment]
> @mmaelicke I will approve when you had a look at my previous comment and also confirm that everything works as expected.

Yeah, thanks! You can appove.

**Review by AlexDo1 — APPROVED** [review]

**Pull request merged**
