### PR TITLE
Add Cli registration interface for extensions

### LINKED ISSUE #263: Register CLI command in extensions
It is currently not possible to register new CLI commands in extensions.

We need that to register a new command which produces ISO19115 XML files via the command line.

### PR DESCRIPTION
**Pull request by mmaelicke**
This PR closes #263
@AlexDo1 can you check this enhancement with an extra branch of the ISO extension? 
There is an example in the docstring. Using extensions does only work for the CLI, if the extensions are activated, which in turn is only possible if there is an importable path to the class. Hence it does not work from a notebook and I did not check the code in action...

### CODE REVIEW

**Comment by AlexDo1** [comment]
I just tried out your example.  
When I run `metacatalog -h`, I get this error message:
```bash
metacatalog -h
Traceback (most recent call last):
  File "/home/alexander/anaconda3/bin/metacatalog", line 33, in <module>
    sys.exit(load_entry_point('metacatalog', 'console_scripts', 'metacatalog')())
  File "/home/alexander/Github/metacatalog/metacatalog/command_line.py", line 105, in main
    extension.init_cli(subparsers=subparsers, defaults=default_options)
TypeError: init_cli() got multiple values for argument 'subparsers'
```
Any idea, should I try something else?

**Comment by mmaelicke** [comment]
I guess that's on me. I'll have a look.

**Comment by AlexDo1** [comment]
I don't know if it helps and if I did everything right, but I also tried to execute `extension.init_cli(subparsers, default_options)` manually, resulting in the following error:

```python
default_options = argparse.ArgumentParser(add_help=False)
default_options.add_argument("--quiet", '-q', action="store_true", help="Suppress any kind of output.")

parser = argparse.ArgumentParser(description="MetaCatalog management CLI", add_help=True)
subparsers = parser.add_subparsers(title="Commands", description="CLI commands", dest='func')

ext.init_cli(subparsers, default_options)
```
```python
TypeError: init_cli() takes 2 positional arguments but 3 were given
```

**Comment by mmaelicke** [comment]
Ok. I can't reproduce your error message and the failing test is also not related. The typing syntax of using the `list[]` instead of `List[]` is not supported for Python 3.7. 
Now, we either need to import some __future__ if possible, or change back to old imported types all over the place. 
I just don't get why this is failing in this PR, as this should be related to the `type-hints` branch. Maybe I created this branch from the wrong one....

**Comment by mmaelicke** [comment]
> Ok. I can't reproduce your error message and the failing test is also not related. The typing syntax of using the `list[]` instead of `List[]` is not supported for Python 3.7.
> Now, we either need to import some **future** if possible, or change back to old imported types all over the place.
> I just don't get why this is failing in this PR, as this should be related to the `type-hints` branch. Maybe I created this branch from the wrong one....

Jep. That's exactly what I did.
So I will close this branch and reopen with the correct base

**Comment by AlexDo1** [comment]
> Ok. I can't reproduce your error message and the failing test is also not related. The typing syntax of using the `list[]` instead of `List[]` is not supported for Python 3.7. Now, we either need to import some **future** if possible, or change back to old imported types all over the place. I just don't get why this is failing in this PR, as this should be related to the `type-hints` branch. Maybe I created this branch from the wrong one....

Okay, I will try again on Monday.

**Pull request closed without merging**
